name: Castor release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Castor
      uses: ZtModArchive/Castor-Build-Action@1.0.0-beta.3
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file_glob: true
        file: "**/*.z2f"
        tag: ${{ github.ref }}
        overwrite: true
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r zt2Mod.zip **/*.z2f
    - uses: Zt-freak/OdinPlusModUploader-GitHub-Action/action.yml@main
      with:
        nexusmod_mod_id: # your ID here
        file: zt2Mod
        version: ${{ github.ref }}
        nexusmod_api_key: ${{ secrets.NEXUSMOD_API_KEY }}
        nexusmod_cookie_nexusid: ${{ secrets.NEXUSMOD_COOKIE_NEXUSID  }}
        nexusmod_cookie_sid_develop: ${{ secrets.NEXUSMOD_COOKIE_SID_DEVELOP  }}